// Copies the tested bookmarklet extractor into the server as a string.
import { readFileSync, writeFileSync } from "fs";
const min = readFileSync(new URL("../../bookmarklet/copy-for-claude.min.js", import.meta.url), "utf8").trim();
writeFileSync(
  new URL("../server/extract-source.js", import.meta.url),
  "// Generated by scripts/build.mjs from bookmarklet/copy-for-claude.js. Do not edit.\n" +
    `export const EXTRACTOR = ${JSON.stringify(min)};\n`,
);
console.log(`server/extract-source.js written (${min.length} chars)`);
